---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates for Ubuntu
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: controllerNode_server
  become: true
  roles:
  - horizon
  - cinder

- hosts: computeNode_server
  become: true
  roles:
  - neutron
